### ISSUE TITLE
Large file fails

### ISSUE THREAD

**Issue by unixjeff** [boranblok/nntpPoster#11]
`2016-02-13 22:47:48,438 DEBUG 5 ExternalProcessWrappers.ExternalProcessWrapperBase - Executing process: [D:\Auto\Tools\WinRAR.exe a -ep1  -m0 -r -v105216000b "D:\Auto\Working\bb0e7e58689e47879ec72e4f5bdd6a74_readyToPost\bb0e7e58689e47879ec72e4f5bdd6a74" "D:\Auto\Working\Default\bb0e7e58689e47879ec72e4f5bdd6a74.mp4"]
2016-02-13 22:48:47,176 INFO 6 nntpAutoposter.IndexerNotifier - Notified indexer that obfuscated release [bb0e7e58689e47879ec72e4f5bdd6a74] is actually [Redacted]
2016-02-13 22:48:48,441 WARN 5 ExternalProcessWrappers.ExternalProcessWrapperBase - No output received for 5 minutes, killing external process.
2016-02-13 22:48:48,441 INFO 5 nntpPoster.UsenetPoster - Deleting processed folder
2016-02-13 22:48:48,841 DEBUG 5 nntpPoster.nntpMessagePoster - Disposing Posting threads.
2016-02-13 22:48:48,842 ERROR 5 nntpAutoposter.AutoPoster - The upload failed to post. Retrying.
System.UnauthorizedAccessException: Access to the path 'D:\Auto\Working\Default\bb0e7e58689e47879ec72e4f5bdd6a74.mp4' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at nntpAutoposter.AutoPoster.PostRelease(WatchFolderSettings folderConfiguration, UploadEntry nextUpload, FileSystemInfo toUpload, Boolean isDirectory) in C:\Users\Ben\Documents\Visual Studio 2015\Projects\NewsPoster\nntpPoster\nntpAutoposter\AutoPoster.cs:line 201
   at nntpAutoposter.AutoPoster.UploadNextItemInQueue() in C:\Users\Ben\Documents\Visual Studio 2015\Projects\NewsPoster\nntpPoster\nntpAutoposter\AutoPoster.cs:line 131`

**Comment by boranblok** [comment]
modify the external process timeout value:
`  
  <InactiveProcessTimeout>5</InactiveProcessTimeout>`

**Comment by unixjeff** [comment]
Was there an update for this issue?

**Comment by boranblok** [comment]
Did you try my suggestion?

**Comment by unixjeff** [comment]
Yes, it does not seem to effect the time limit, I can set to 60 and it still fails

**Comment by boranblok** [comment]
what error are you getting?

because if it still says `No output received for 5 minutes, killing external process.` then you're probably editing the wrong config file.

**Comment by unixjeff** [comment]
When it RAR's a large file like 5gb+ it takes to long to RAR and ends with that error

**Comment by boranblok** [comment]
so, it still says 5 minutes, despite you having modified the config to 60 minutes. This means that you have modified the wrong config file.

What config file are you modifying the setting in ?

**Comment by unixjeff** [comment]
I am modifying the setting.config in /0.7.0/settings.config it reads as the code below

 <InactiveProcessTimeout>60</InactiveProcessTimeout>

**Comment by boranblok** [comment]
Either you copy/pasted wrong or modified the xml outside of the tags.

The setting is this by default:

`<!-- How many minutes to wait on new output from an external process. --> <InactiveProcessTimeout>5</InactiveProcessTimeout>`

and needs to be changed to this (for a 60 minute timeout)

`<!-- How many minutes to wait on new output from an external process. --> <InactiveProcessTimeout>60</InactiveProcessTimeout>`

**Comment by unixjeff** [comment]
Sorry, Yes I did copy and paste incorrect. I have the code you provide listed

**Comment by boranblok** [comment]
so you have that, and the error still complains about a 5 minute timeout?

if you change other settings do those work ? (like put an invalid usenet address on purpose for instance)
