### ISSUE TITLE
Keep getting this error message, please help

### ISSUE THREAD

**Issue by LoveLace55** [boranblok/nntpPoster#51]
System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at ExternalProcessWrappers.ExternalProcessWrapperBase.ExecuteProcess(String parameters) in C:\Users\BoB\source\repos\nntpPoster\ExternalProcessWrappers\ExternalProcessWrapperBase.cs:line 78
   at ExternalProcessWrappers.RarWrapper.Compress(FileSystemInfo source, DirectoryInfo destination, String archiveName, Int32 partSize, String password, String extraParams) in C:\Users\BoB\source\repos\nntpPoster\ExternalProcessWrappers\RarWrapper.cs:line 49
   at nntpPoster.UsenetPoster.MakeRarAndParFiles(FileSystemInfo toPost, String nameWithoutExtension, DirectoryInfo processedFolder, String password) in C:\Users\BoB\source\repos\nntpPoster\nntpPoster\UsenetPoster.cs:line 165
   at nntpPoster.UsenetPoster.PostToUsenet(FileSystemInfo toPost, String title, String rarPassword, Boolean saveNzb) in C:\Users\BoB\source\repos\nntpPoster\nntpPoster\UsenetPoster.cs:line 57
   at nntpPoster.UsenetPoster.PostToUsenet(FileSystemInfo toPost, String rarPassword, Boolean saveNzb) in C:\Users\BoB\source\repos\nntpPoster\nntpPoster\UsenetPoster.cs:line 39
   at nntpAutoposter.AutoPoster.PostRelease(WatchFolderSettings folderConfiguration, UploadEntry nextUpload, FileSystemInfo toUpload, Boolean isDirectory) in C:\Users\BoB\source\repos\nntpPoster\nntpAutoposter\AutoPoster.cs:line 174
   at nntpAutoposter.AutoPoster.UploadNextItemInQueue() in C:\Users\BoB\source\repos\nntpPoster\nntpAutoposter\AutoPoster.cs:line 131

**Comment by boranblok** [comment]
obviously access is denied to whatever you have configured as rar executable.

**Comment by LoveLace55** [comment]
I didn't install winrar, just unzipped all the items in a rar folder. Trying to keep it portable.

but where does this BoB user comes from ? I don't have that in the system

**Comment by boranblok** [comment]
that is the stack trace information. It was compiled on a machine by a user named BoB.

The nntpPoster tries to execute rar ....parameters.... if needs to find that on the path and have permission to execute it.

so if you work with relative paths you have to ensure the current application path is also the path with the rar executable.

**Comment by LoveLace55** [comment]
I only need rar.exe ?

**Comment by boranblok** [comment]
well, and all the other suff rar.exe needs to run itself, that application probably has DLL's config files etc as well, I am no expert in running rar portable.

**Comment by LoveLace55** [comment]
Well, even a newbie can help...

rar.exe works well on it's own... hehe :)

Now you know.... :)

Thank you for this wonderful software and your effort to maintain it, +Karma for you

**Comment by LoveLace55** [comment]
Ok, This worked perfectly the first time... But now the program doesn't seem to pick up the folder in the watch folder... It just stays there when I launch nntpposter autoposter
